"""Add created_at & updated_at columns + redo transactions table.

Revision ID: 577f8f9be734
Revises: 7fc40d47646c
Create Date: 2023-02-27 18:31:34.461926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577f8f9be734'
down_revision = '7fc40d47646c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_account_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_bank_account_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('transactions', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.drop_column('external_id')
        batch_op.drop_column('bank_account_id')

    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('bank_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_connections', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('bank_account_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('transactions')
        batch_op.drop_column('external_bank_account_id')

    # ### end Alembic commands ###
