"""Initial migration.

Revision ID: 7fc40d47646c
Revises: 
Create Date: 2023-02-24 11:49:39.266528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fc40d47646c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_account_transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('bank_account_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('bank_connection_id', sa.String(), nullable=False),
    sa.Column('bank', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('iban', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_connections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bank', sa.String(length=120), nullable=False),
    sa.Column('national_identification_number', sa.String(length=60), nullable=False),
    sa.Column('access_token', sa.String(length=140), nullable=False),
    sa.Column('refresh_token', sa.String(length=140), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_connections')
    op.drop_table('bank_accounts')
    op.drop_table('bank_account_transactions')
    # ### end Alembic commands ###
