version: "3.9"

volumes:
  database:
  financial-information-service:
  bank-integration-service:

services:
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    command: ""
    healthcheck:
      test: "exit 0"
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 5s

  bank-integration-service:
    image: python:3.8-alpine
    restart: always
    environment:
      FLASK_ENV: development
      DB_HOST: database
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: financial
      SEB_CLIENT_ID: id_here
      SEB_CLIENT_SECRET: secret_here
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ../bank-integration-service:/home/app
    working_dir: /home/app
    command: sh -c "apk add libpq-dev && apk add build-base && pip install -r requirements.txt && flask db upgrade && python app.py"
    ports:
      - 5000:5000
    healthcheck:
      test: "exit 0"
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 30s

  financial-information-service:
    image: node:16-alpine
    restart: always
    environment:
      WEB_SERVER_PORT: 3000
      BANK_INTEGRATION_SERVICE_URL: bank-integration-service:5000
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: application
      DB_HOST: database
      NODE_ENV: development
      SERVER_SECRET: high_security
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ../financial-information-service:/home/app
    working_dir: /home/app
    command: sh -c "npm install --global pnpm prisma && pnpm install && npx prisma db push && pnpm run dev"
    ports:
      - 3000:3000
    healthcheck:
      test: "exit 0"
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 30s
